/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAuditsIndexRouteImport } from './routes/_authenticated/audits.index'
import { Route as AuthenticatedAuditsIdRouteImport } from './routes/_authenticated/audits.$id'
import { Route as AuthenticatedAuditsNewRouteImport } from './routes/_authenticated/audits.new'
import { Route as AuthenticatedAuditsIdReportRouteImport } from './routes/_authenticated/audits.$id.report'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditsIndexRoute =
  AuthenticatedAuditsIndexRouteImport.update({
    id: '/audits/',
    path: '/audits/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditsIdRoute = AuthenticatedAuditsIdRouteImport.update({
  id: '/audits/$id',
  path: '/audits/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditsNewRoute = AuthenticatedAuditsNewRouteImport.update({
  id: '/audits/new',
  path: '/audits/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditsIdReportRoute =
  AuthenticatedAuditsIdReportRouteImport.update({
    id: '/report',
    path: '/report',
    getParentRoute: () => AuthenticatedAuditsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/audits/$id': typeof AuthenticatedAuditsIdRouteWithChildren
  '/audits/new': typeof AuthenticatedAuditsNewRoute
  '/audits/': typeof AuthenticatedAuditsIndexRoute
  '/audits/$id/report': typeof AuthenticatedAuditsIdReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/audits/$id': typeof AuthenticatedAuditsIdRouteWithChildren
  '/audits/new': typeof AuthenticatedAuditsNewRoute
  '/audits': typeof AuthenticatedAuditsIndexRoute
  '/audits/$id/report': typeof AuthenticatedAuditsIdReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/audits/$id': typeof AuthenticatedAuditsIdRouteWithChildren
  '/_authenticated/audits/new': typeof AuthenticatedAuditsNewRoute
  '/_authenticated/audits/': typeof AuthenticatedAuditsIndexRoute
  '/_authenticated/audits/$id/report': typeof AuthenticatedAuditsIdReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/audits/$id'
    | '/audits/new'
    | '/audits/'
    | '/audits/$id/report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/audits/$id'
    | '/audits/new'
    | '/audits'
    | '/audits/$id/report'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/audits/$id'
    | '/_authenticated/audits/new'
    | '/_authenticated/audits/'
    | '/_authenticated/audits/$id/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audits/': {
      id: '/_authenticated/audits/'
      path: '/audits'
      fullPath: '/audits/'
      preLoaderRoute: typeof AuthenticatedAuditsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audits/$id': {
      id: '/_authenticated/audits/$id'
      path: '/audits/$id'
      fullPath: '/audits/$id'
      preLoaderRoute: typeof AuthenticatedAuditsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audits/new': {
      id: '/_authenticated/audits/new'
      path: '/audits/new'
      fullPath: '/audits/new'
      preLoaderRoute: typeof AuthenticatedAuditsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audits/$id/report': {
      id: '/_authenticated/audits/$id/report'
      path: '/report'
      fullPath: '/audits/$id/report'
      preLoaderRoute: typeof AuthenticatedAuditsIdReportRouteImport
      parentRoute: typeof AuthenticatedAuditsIdRoute
    }
  }
}

interface AuthenticatedAuditsIdRouteChildren {
  AuthenticatedAuditsIdReportRoute: typeof AuthenticatedAuditsIdReportRoute
}

const AuthenticatedAuditsIdRouteChildren: AuthenticatedAuditsIdRouteChildren = {
  AuthenticatedAuditsIdReportRoute: AuthenticatedAuditsIdReportRoute,
}

const AuthenticatedAuditsIdRouteWithChildren =
  AuthenticatedAuditsIdRoute._addFileChildren(
    AuthenticatedAuditsIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAuditsIdRoute: typeof AuthenticatedAuditsIdRouteWithChildren
  AuthenticatedAuditsNewRoute: typeof AuthenticatedAuditsNewRoute
  AuthenticatedAuditsIndexRoute: typeof AuthenticatedAuditsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAuditsIdRoute: AuthenticatedAuditsIdRouteWithChildren,
  AuthenticatedAuditsNewRoute: AuthenticatedAuditsNewRoute,
  AuthenticatedAuditsIndexRoute: AuthenticatedAuditsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
